#!/bin/sh
# Copyright 2009-2016 RackTop Systems Inc. and/or its affiliates.
# http://www.racktopsystems.com
#
# The methods and techniques utilized herein are considered TRADE SECRETS
# and/or CONFIDENTIAL unless otherwise noted. REPRODUCTION or DISTRIBUTION
# is FORBIDDEN, in whole and/or in part, except by express written permission
# of RackTop Systems.
#
# @@DESCRIPTION@@  A minimal wrapper selecting subset of ZFS properties.
# @@NAME@@         selectprops
# @@STABILITY@@    unstable
# @@VERSION@@      1.0.0
#
# If this was enabled via envvar. enable tracing globally and in functions.
DEBUG="${DEBUG:-0}"
[[ "${DEBUG}" -gt 0 ]] && set -o xtrace

if [[ -z $1 ]] ; then exit 1 ; fi

POOL=p01
ROOTDS=${POOL}/global
AGPROP=hac:acl:allowed_groups
AUPROP=hac:acl:allowed_users
# Adjust this list of props, adding or subtracting props as necessary.
# Use comma as a delimiter without any spaces.
FIELDS="usedbydataset,available,used,logicalused,${AGPROP},${AUPROP}"

/usr/racktop/sbin/fsadm -j zp get -f --fields="${FIELDS}" "${ROOTDS}/$1"
